### PR TITLE
Add script develop-install-windows.ps1

### PR DESCRIPTION
**Pull request by leon-vv**

### CODE REVIEW

**Comment by jobdewitte** [comment]
I've checked on Windows and the develop install works fine now. However, it creates a traceon_backend.pyd that would need to be commited again. Is this expected behavior?

**Comment by jobdewitte** [comment]
> I've checked on Windows and the develop install works fine now. However, it creates a traceon_backend.pyd that would need to be commited again. Is this expected behavior?

Spoke too soon. It seemed to work initially, but now on a new branch I get the same issue again.

**Comment by leon-vv** [comment]
Good point, I've added `*.pyd` to `.gitignore`

**Review by jobdewitte — APPROVED** [review]
Perfect! I will approve.

**Pull request merged**
